### ISSUE TITLE
ist Req auf heimrichhannot/contao-utils-bundle notwendig?

### ISSUE THREAD

**Issue by zonky2** [heimrichhannot/contao-loginredirects-bundle#3]
Mit dem Paket kommt so viel "Zeug" - insbesondere JS - mit, der dann auch automatisch geladen wird und häufig den "page speed" drückt - ggf. ist die Einbindung gar nicht notwenditg oder leicht zu umgehen...

**Comment by Defcon0** [comment]
Zitat README.md:

```
huh_utils:
# Load utils bundle assets. Default value will be changed to false in next major version.
  enable_load_assets:   true
```

**Comment by zonky2** [comment]
öhm... sehe ich nicht :(
https://github.com/heimrichhannot/contao-loginredirects-bundle/blob/master/README.md

**Comment by Defcon0** [comment]
In der README vom utils-bundle...

Trotzdem habe ich mal eine Version ohne utils gebaut, da es hier wirklich nur genau 1-mal gebraucht wurde. In dem Fall ist es verzichtbar.

**Comment by zonky2** [comment]
>Trotzdem habe ich mal eine Version ohne utils gebaut

ist aber noch nicht gepushed - oder?

**Comment by Defcon0** [comment]
Etwas Geduld bitte....... :-) Packagist braucht seine Zeit...

https://github.com/heimrichhannot/contao-loginredirects-bundle/tree/1.0.3
https://packagist.org/packages/heimrichhannot/contao-loginredirects-bundle
