### ISSUE TITLE
PHP 8 compatibility?

### ISSUE THREAD

**Issue by Webstylerin** [heimrichhannot/contao-loginredirects-bundle#5]
Hi,

are there any plans to get the extension ready for PHP 8?

Regards,
Nicole

**Comment by koertho** [comment]
We don't plan such things, we update them as needed :) 
I can't promise a quick update here, as I'm very busy before I go on vacation in the next days :)

**Comment by zonky2** [comment]
Hi @koertho I hope your busy days have subsided after half a year and you can take over the PR #6 ;-)

**Comment by koertho** [comment]
@zonky2 Never :D
I merged the PR and now you can use this bundle with php 8 ;)
